### PR TITLE
Support columns with dots

### PR DESCRIPTION
**Pull request by vampolo**
Suppose you have an array of object of data that you want to display

```
let data = [{
  'a.b': 1
},{
  'a.b': 2
}]
```

powerPick function will interpret 'a.b' as a path and will try to access
data.a.b while it should simply access data['a.b'].

This commit fixes this behavior and thus the issue #228

### CODE REVIEW

**Comment by kevinold** [comment]
@vampolo Please update your branch with the latest master which includes #241. This will allow your tests to run on Travis.  Thanks!

**Comment by jesusoterogomez** [comment]
Are there any plans to merge this PR any time soon?. I'm also in dire need of this feature.

**Comment by Dem0n3D** [comment]
I suggest to move this patch in getPath(obj, ks), because in powerPick (object, keys) it not used by sorting #380.

**Comment by vampolo** [comment]
Closing this as it has been merged in #380

**Pull request closed without merging**
