### PR TITLE
Multiple selection

### PR DESCRIPTION
**Pull request by cosminnicula**
- does not support subgrids
- the selection is reset when sorting / paging / filtering
- the selection is not reset when paging with infinite scroll

### CODE REVIEW

**Comment by bjrmatos** [comment]
cool!!!

**Comment by ryanlanciaux** [comment]
Thanks so much! This is quite nice! :+1:

**Comment by bjrmatos** [comment]
@ryanlanciaux i've just found that React throws a warning when using this new feature.. and that is because the new column (checkbox column) not have a key property.

**Comment by bjrmatos** [comment]
warnings

**Comment by bjrmatos** [comment]
Also this breaks support for React 0.12.x, because of the use of `React.findDOMNode` in `handleSelectClick` method in `gridRow.jsx file

**Comment by ryanlanciaux** [comment]
Thanks for the heads-up @bjrmatos -- that _should_ be fixed now :+1:

**Pull request merged**
