### PR TITLE
Improvements to column filter functions

### PR DESCRIPTION
**Pull request by dankrieger**
Adding support for column filter function to support an array of values to be filtered by
Adding columnFilterFunc prop to allow customized column filter

Provides resolution of issues: #482 #490

### CODE REVIEW

**Comment by dankrieger** [comment]
Any chance for some feedback on this PR?  If I resolve the branch conflicts can we expect it to be merged in an upcoming version?

**Comment by ryanlanciaux** [comment]
Yes definitely! So sorry about the delay -- we were having a bit of trouble managing time between getting the release for 1.0 and maintaining v0. This is starting to slow down a bit but one of us will definitely take a deeper look and work at getting this merged.

It looks great so far -- thanks for taking the time to do this and again sorry about the delay on our end!

**Comment by ryanlanciaux** [comment]
Also if the only thing is build that's conflicting I think you can just get the rest of the files ahead of v0 and then rebuild and it _should_ be good.

**Comment by Tsvetkovv** [comment]
@ryanlanciaux hello! Is implementing column filter in progress for v1? I found unused  `GRIDDLE_SET_FILTER_BY_COLUMN` constant

**Comment by dankrieger** [comment]
I rebased against v0 and found some weird committed conflicts in the compiled modules that I tried integrating into the main branch so they are retained.

**Pull request merged**
