### PR TITLE
Conditional Columns #656

### PR DESCRIPTION
**Pull request by andreme**
Implement #656

### CODE REVIEW

**Comment by dahlbyk** [comment]
Thanks!

**Comment by andreme** [comment]
@dahlbyk Thanks. Is there any chance to get a release soon (especially for the fixed bugs)?

**Comment by dahlbyk** [comment]
> Is there any chance to get a release soon (especially for the fixed bugs)?

That's up to @ryanlanciaux availability.

**Comment by ryanlanciaux** [comment]
Thanks everyone for the updates here! 1.5.0 is on npm but not the "@latest" version. I am running into an issue on the docs that I'm trying to down when I use `1.5.0` (could be unrelated) but once that is sorted out, will push as "@latest" tag also.

**Pull request merged**
