### PR TITLE
Custom filterComponent and filter function

### PR DESCRIPTION
**Pull request by tinygrasshopper**
The pull request enables
- The ability of specify a custom filter component, to enable
  - Building complex filter inputs, filters with more components than the simple text box
  - Faceting, the result set is passed down to the filter, so that the filter can change according to what is selected.

- The ability to specify a custom filter function, to enable
  - Swapping out the underscore based filterer, to a more performant alternative. 
  - Enables consumption of the custom filter object that the customFilterComponent might create.

### CODE REVIEW

**Comment by kevinold** [comment]
@tinygrasshopper Please update your branch with the latest master which includes #241. This will allow your tests to run on Travis.  Thanks!

**Comment by Funfun** [comment]
@tinygrasshopper nice work!

**Comment by tinygrasshopper** [comment]
@kevinold any thoughts on the pull-request? Is it clear how one might use these extensions? Should I include some sample code, on how we use this to build filters based on the results?

**Comment by Funfun** [comment]
@kevinold Please review PR if its possible.

**Comment by kevinhughes27** [comment]
would love to see this functionality added!

**Comment by OliDM** [comment]
When is this getting merged?

**Comment by kevinold** [comment]
@tinygrasshopper Please update to the latest master and I will get this merged this weekend.  Thanks!

**Comment by tinygrasshopper** [comment]
@kevinold Updated

**Comment by vjustov** [comment]
+1. When is this getting merged?

**Comment by kevinhughes27** [comment]
looks like this has been updated - any word on getting this merged?

**Comment by ryanlanciaux** [comment]
Seems good

**Comment by Funfun** [comment]
:cake:

**Comment by kevinhughes27** [comment]
:clap:

**Comment by OliDM** [comment]
:+1:

**Comment by dana2208** [comment]
hello @tinygrasshopper ,
can you include some sample code, on how we use this to build filters based on the results as you suggested?

**Pull request merged**
