### PR TITLE
Add support for creating colouns for nested fields

### PR DESCRIPTION
**Pull request by saary**
After this change users will be able to add columns which values are nested fields.
For example consider the following data structure:
```javascript
[
  {
     obj: {
       a: {
         b: 'some internal value'
       }
     }
  }
]
```

You can now set a column named `obj.a.b` in order to show `b` values in a column.

### CODE REVIEW

**Comment by saary** [comment]
@ryanlanciaux , @joellanciaux - I was not able to run the tests on a Windows machine.
I have tested it worked on the examples and on my own site, but the tests need to be run.

Thanks,
-saar

**Comment by saary** [comment]
ping?

**Comment by ryanlanciaux** [comment]
Hey @saary thanks for doing this and sorry about the delay. We will likely get this merged today.

**Comment by saary** [comment]
:+1:  Thanks!

**Comment by joellanciaux** [comment]
Merged. Thanks again! :+1:

**Pull request merged**
