### PR TITLE
Overcome "Empty table header" accessibility error

### PR DESCRIPTION
**Pull request by liorbentov**
See http://webaim.org/techniques/tables/data

### CODE REVIEW

**Comment by liorbentov** [comment]
@ryanlanciaux, can you take a look?

**Comment by ryanlanciaux** [comment]
Sorry about the delay -- Haven't had much time to devote to this yet (been traveling). Will try to soon! Thanks for adding this.

**Comment by ryanlanciaux** [comment]
I'd like to be better at accessibility and I am not sure I fully understand. Is the main reasoning here that we want to display a td if there is no text for accessibility?

**Comment by liorbentov** [comment]
@ryanlanciaux, Yes, we need to display td when the th is empty.
Please take a look at https://www.w3.org/TR/WCAG20-TECHS/F46.html

**Comment by ryanlanciaux** [comment]
Awesome - thanks for the info and for creating this PR. 👍

**Pull request merged**
