### PR TITLE
Update babel eslint

### PR DESCRIPTION
**Pull request by ryanlanciaux**
* Use babel instead of 6to5 (long time coming on that)
* Add basic eslint and fix some code formatting issues.

### CODE REVIEW

**Comment by kevinold** [comment]
@ryanlanciaux I see you're using Babel-jest as your preprocessor and think that might be why jest is failing. Any reason you're using that over the simple preprocessor from the jest site?

Customized setup from here
https://facebook.github.io/jest/docs/tutorial-react.html

**Comment by kevinold** [comment]
@ryanlanciaux FYI, testing this now to see if it fixes the issue with travis https://github.com/kevinold/Griddle/commit/18cedd735531d4972ef3fa4bc7e804023a6d353d

Results will be here:
https://travis-ci.org/kevinold/Griddle/builds/81275797

FWIW, I'm still seeing failing tests for griddle-tests.js on this branch.

screen shot 2015-09-20 at 1 23 19 pm

**Comment by kevinold** [comment]
Odd mine is failing with the same error

**Comment by kevinold** [comment]
I think this might be the answer: https://github.com/kevinold/Griddle/commit/7baef2c8010ceb553f1f12aaff4b599bf7d087af

**Comment by kevinold** [comment]
@ryanlanciaux Bingo!  jest now runs on travis and shows failing tests.  I'd suspect these are failing on node v4 locally too, but haven't tested yet.

https://travis-ci.org/kevinold/Griddle/builds/81280357

**Comment by ryanlanciaux** [comment]
Ah ha! Awesome thanks! I will get this switched around and hopefully fix the tests :) Seriously thanks a ton for looking into this!

**Pull request closed without merging**
