### PR TITLE
Fix for issue #184

### PR DESCRIPTION
**Pull request by ttrentham**
Use _.extend instead of Object.create to preserve data

### CODE REVIEW

**Comment by kevinold** [comment]
@ttrentham Please update your branch with the latest master which included #241.  This will allow your tests to run on Travis.

**Comment by ttrentham** [comment]
@kevinold Merged as requested. Though I have problems running the tests locally still for some reason.

hqttrentham901:Griddle ttrentham$ npm test

> griddle-react@0.2.14 test /Users/ttrentham/Github/Griddle
> jest


 == UPGRADE NOTICE ==
 Node and io.js will be merging. http://bit.ly/1dOjLVK
 Please upgrade to Jest 0.5.x if you wish to use iojs.
 Jest 0.4.x will continue to work on Node and receive bugfixes
Using Jest CLI v0.4.19
 FAIL  __tests__/griddle-test.js
Error: Worker process exited before responding! exit code: null, exit signal: SIGSEGV
stderr:


A worker process has quit unexpectedly! This is bad news, shutting down now!
npm ERR! Test failed.  See above for more details.

**Comment by kevinold** [comment]
@ttrentham I'm seeing the same issue locally with jest tests, but travis seems to run them.  I'll review your commit now that tests are passing and see if we can get it merged.

**Comment by ttrentham** [comment]
It's a node version issue. I'm using 0.12.x for development of my current project. If you switch back to 0.10.36, it works. I use n to switch between node installs for stuff like this.

**Pull request merged**
