### PR TITLE
feature request: allow a custom componentDidMount() method to be passed

### PR DESCRIPTION
**Pull request by jblossom-denver**
this would be useful, in case one needs to interact with the DOM after the Griddle table is rendered

### CODE REVIEW

**Comment by ryanlanciaux** [comment]
Thanks for adding this :+1:

**Comment by jblossom-denver** [comment]
@ryanlanciaux no problem, thanks for merging!

**Comment by jblossom-denver** [comment]
@ryanlanciaux will this go into a release and published to npm any time soon? thanks

**Comment by ryanlanciaux** [comment]
So sorry about the delay -- it should be in the next couple of days.. trying to determine if there is anything that belongs in this release or if it'd be better to just push this out and follow up with another point release a little later on.

**Comment by jblossom-denver** [comment]
@ryanlanciaux no worries, thanks for the update. If you ship before I do, I won't have to manage a fork. So I can sit tight for a few days if needed

**Comment by jblossom-denver** [comment]
@ryanlanciaux any updates? thanks :)

**Pull request merged**
