### PR TITLE
lock react version to 0.13.3

### PR DESCRIPTION
**Pull request by kevinold**

### CODE REVIEW

**Comment by jjstrat3** [comment]
I'm sorry but why do this?  I tried installing Griddle@master branch on a project that I have running React 0.14, and this commit prevents that.

**Comment by kevinold** [comment]
@jjstrat3 Correct, this enforces React 0.13.3 as the codebase as not been upgraded to support 0.14 officially.  The package definition for React allowed 0.14 to be installed automatically and lead to failing tests.  Apologies for any inconvenience.

**Comment by kevinhughes27** [comment]
it was working fine for me ... any eta on getting the version bumped? anything we can do to help?

**Comment by ryanlanciaux** [comment]
A PR upgrading to .14 would be awesome. That said, if no one else takes that on, we're planning to upgrade to 0.14 soon. Sorry about any delays -- been a bit swamped.

**Pull request merged**
