### PR TITLE
fixed PropTypes warnings due to upcoming deprecation in React v15.5

### PR DESCRIPTION
**Pull request by followbl**
https://github.com/GriddleGriddle/Griddle/issues/651

There's still an error in the console on the *storybook*...but after this, it's been determined the culprit is a non-upgraded dependency in @kadira/storybook

```brad@~ Griddle (issue-651) $ yarn why react-inspector
yarn why v0.23.3
[1/4] 🤔  Why do we have the module "react-inspector"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info This module exists because "@kadira/storybook#@kadira/storybook-addon-actions" depends on it.
info Disk size without dependencies: "208kB"
info Disk size with unique dependencies: "1.23MB"
info Disk size with transitive dependencies: "20MB"
info Amount of shared dependencies: 32
✨  Done in 0.97s.```

### CODE REVIEW

**Comment by followbl** [comment]
to be clear, this does fix the console errors in the Griddle package, which was the goal of this PR/issue ;)

**Comment by followbl** [comment]
@dahlbyk yea. funny enough I blew away the yarn.lock and added `prop-types` a second time and it insisted on updating the yarn.lock file like so...I agree, weird

**Comment by ryanlanciaux** [comment]
Awesome thank you!

**Comment by juampick** [comment]
Hi! Thanks for this update. Do you know @ryanlanciaux when are we going to have a new release version? I'm using `1.4.0` and still has this issue. 

Thanks a lot.

**Pull request merged**
