### PR TITLE
fix gridRow defaultValue logic

### PR DESCRIPTION
**Pull request by odk211**
`fromPairs` does not work.
https://github.com/GriddleGriddle/Griddle/commit/b65bfe8460848f6e3a1a7942c4b1c3ae3c9f4255#diff-486930079516b14efdf7e2572b02c647R83

### CODE REVIEW

**Comment by odk211** [comment]
I want to use griddle 0.5.0 but this regression prevent from it.
Could you check it ? and I hope this patch is released.

**Comment by ryanlanciaux** [comment]
Awesome -- thanks so much for adding this. I'll try to test this out tonight

**Comment by odk211** [comment]
@ryanlanciaux Thanks! It's not a hurry, I use my fork now.
When the latest is released, I use :)

**Comment by odk211** [comment]
rebased, but I'm not sure why `build/Griddle.js` diff is so huge :(

**Pull request closed without merging**
