### PR TITLE
v0: fix React.createClass and PropTypes for react 16

### PR DESCRIPTION
**Pull request by vakopian**
## Griddle major version
v0 (0.8.1)

## Changes proposed in this pull request
use `createReactClass` from `create-react-class` package and `PropTypes` from `prop-types` package.

## Why these changes are made
Make it compatible with React 16

### CODE REVIEW

**Comment by ryanlanciaux** [comment]
Awesome! Thanks a ton for adding this -- will give it a test locally and try to get a new version 0.8.2 out this weekend 👍

**Comment by adamsproul** [comment]
Any updates on this?

**Comment by thathenderson** [comment]
Any idea if this will be released soon? Anything pending that I could potentially help with?

**Comment by dahlbyk** [comment]
@adamsproul @thathenderson have you been able to confirm these updates work on your projects? I assume @ryanlanciaux just hasn't had a chance to provide a second opinion on the proposal.

**Comment by thathenderson** [comment]
@dahlbyk Sorry for the delay in responding. Confirmed that this pr (at least on my end) silences all PropTypes and createClass warnings in React 15.5 and works as expected in React 16.

**Comment by thathenderson** [comment]
Is there anything else I could help with in order to cut a 0.8.2 release?

**Comment by thathenderson** [comment]
Happy New Year everyone!

Anything new on this? It's the last dependency in our project we need to fix in order to support React 16.

**Comment by adamsproul** [comment]
Happy New Year.

We unfortunately had to move away from using griddle
 because of this. Hopefully you have better luck.

**Comment by mpolinowski** [comment]
I also love Griddle - but to continue adding it to a project, I would need React16 support.  Is there still an issue somewhere that needs to be resolved before merging this?

**Comment by danielericlee** [comment]
Hi @ryanlanciaux, any chance that we could get this merged into the v0 branch and released?

Like other folks on this thread, my company is pushing to upgrade our apps to React 16, but don't have bandwidth to port to Griddle 1.0.

Thank you for the awesome utility!

**Comment by thathenderson** [comment]
Pinging this thread once more. It would be really great to get this in! @ryanlanciaux

**Comment by yang-wei** [comment]
lets merge this

**Comment by yang-wei** [comment]
Thanks for merging this. Can you let me know when is this version is going to be published on npm ?

**Comment by dahlbyk** [comment]
> I believe this is affecting the v1 branch as well - I am seeing the same warnings in v1.11.2.
> Any info on when the changes will published to v1?

We've had a quite a few React 16 fixes that are available in [`griddle-react@1.13.0`](https://www.npmjs.com/package/griddle-react?activeTab=versions), that version just hasn't been marked as `latest`.

**Comment by dahlbyk** [comment]
[`griddle-react@0.8.2`](https://www.npmjs.com/package/griddle-react?activeTab=versions) has been published with this fix, but I'm not 100% confident because the build is red. Can anyone confirm it works for you?

**Pull request merged**
