### PR TITLE
add onSelectionChange and persist selectedRowIds across pages

### PR DESCRIPTION
**Pull request by babenzele**
I've implemented an onSelectionChange callback that the user can use. I needed it for a project of mine and couldn't figure out how to get Griddle 1.0 working, so here are my changes. 

A number of these changes are cosmetic, the formatting in the existing multiple selection code was pretty inconsistent.

I don't know why my `.js` files are so much longer than other peoples' changes, but this is what I got when I built with grunt. 

Please let me know if you have any questions or issues with these commits.

### CODE REVIEW

**Comment by babenzele** [comment]
For reference: #125, #144, #151, #153, #175, #218, #230, #234

**Comment by ryanlanciaux** [comment]
Thanks so much - one of us will test it out a bit more and try to get things merged + published today / tomorrow.

**Comment by joellanciaux** [comment]
Thank you for putting this together! :+1:

**Comment by babenzele** [comment]
You got it!

**Comment by nickwang14** [comment]
Is there documentation on how to implement this when using griddles?  I don't see any references to checkboxes in the documentation.

Note: I saw current documentation is v0, does that mean these changes have been merged but not released?

**Comment by dahlbyk** [comment]
I never worked with Griddle 0.x, so I can't speak to this feature, but this appears to be part of v0.8.2 (#809).

As far as I know v1 doesn't have an equivalent feature.

**Pull request merged**
