### PR TITLE
Stop sorting internally if using external sort

### PR DESCRIPTION
**Pull request by flamerohr**
Had some issues where the internal sorting wasn't agreeing with external sort order given, I could've patched this with a custom sort function... but I think this is a cleaner approach. (and less code duplication for when my sorting happens on the server)

### CODE REVIEW

**Comment by tractorcow** [comment]
As an alternative to this, I would love it if it were possible to access the root objects being sorted in customCompareFn.

E.g.

`return customCompareFn(a, b);`

vs current 

`return customCompareFn(_get(a, column), _get(b, column));`

Then we could do somehing like

```json
{
	columnName: size,
	customCompareFn: (a, b) => ((a.size * a.unitModifier) - (b.size * b.modifier));
}
```

**Comment by tractorcow** [comment]
I found a work-around for @flamerohr 's use case. You can use the below to disable re-sorting of values.

```
{
        columnName: 'title',
        customCompareFn: () => (0), // Disable custom sorting
},
```

**Comment by flamerohr** [comment]
Yes, the workaround is available, but it would require defining for every column, which is not ideal when you've got server-side sorting by use of externalSort, etc.

Access to the row data would be very handy for the customCompare endpoint.

**Comment by robababa** [comment]
+1 for this PR.  Ran into the same issue.  We get data from an external REST API, and when the user changes sorting, we re-fetch data from the REST endpoint, because we use pagination.  Unfortunately, the user sees the old data re-sorted before the new data arrives.  This PR would fix that.

Specifically, when the user clicks a column header to change sorting, it invokes the external function, which creates the action to change the sort parameters in Redux.  The parent container then runs its `componentDidUpdate()` method to request new data from the REST endpoint.  In the meantime, unfortunately, the Griddle component re-sorts the old data, and the user sees this before the new data from the REST endpoint arrives.

**Pull request merged**
